

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# CD
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    # CI
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    # npm module에 변경사항이 있을 경우만 설치하도록 조건문 -> 조건문으로 안하면 push할때마다 설치한다 -> 불필요
    # if: steps.cache.outputs.cache-hit != 'true'
    - run: npm install



